### PR TITLE
Porting to windows

### PR DESCRIPTION
**Pull request by brawner**
This PR makes further adjustments to rqt for compatibility on Windows.

Depends on https://github.com/ros-visualization/qt_gui_core/pull/162

### CODE REVIEW

**Review by mlautman — APPROVED** [review]
Looks good to me

**Comment by brawner** [comment]
@dirk-thomas Any comments on this PR?

**Review by dirk-thomas — COMMENTED** [review]
The patch looks reasonable but it should pass building on CI before being merged. Since it requires installing the dependencies on the Windows nodes it might be a while until I get to it.

**Comment by brawner** [comment]
Ok, let me know when you get to that and I can help out where needed.

**Comment by ahcorde** [comment]
This PR is targeting Crystal, and I think this is already working on Windows. Closing this PR

**Pull request closed without merging**
