### PR TITLE
Use underscores instead of dashes in `setup.cfg`

### PR DESCRIPTION
**Pull request by aprotyas**
New `python3-setuptools` warns about this.

Signed-off-by: Abrar Rahman Protyasha <abrar@openrobotics.org>

### CODE REVIEW

**Review by clalancette — COMMENTED** [review]
While we are in here, can you add the `[develop]` section that every other setup.cfg script in our tree has (e.g. https://github.com/ros-visualization/rqt_top/blob/crystal-devel/setup.cfg)?  That will just make it consistent.  Thanks!

**Comment by aprotyas** [comment]
> While we are in here, can you add the `[develop]` section that every other setup.cfg script in our tree has (e.g. https://github.com/ros-visualization/rqt_top/blob/crystal-devel/setup.cfg)? That will just make it consistent. Thanks!

Done in 6003fa1. I'm not sure about the CI failure though.
___

On a semi-related note, @clalancette is there a tracker for this Humble project item? [`script-dir` and `install-scripts` will not be supported in future versions](https://github.com/orgs/ros2/projects/23#card-58333054)
I was looking at whether other packages need the same treatment as this PR. Results from today's source checkout (including the changes in this PR):
```bash
[09:31 abrar@open-robotics: ~]$ egrep -r --include=setup.cfg '(script-dir|install-scripts)' ~/ros2_rolling/src
[09:31 abrar@open-robotics: ~]$ 
```

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
We can ignore the CI failure on Dashing; that is vestigial and should go away soon.

**Comment by clalancette** [comment]
> On a semi-related note, @clalancette is there a tracker for this Humble project item? [`script-dir` and `install-scripts` will not be supported in future versions](https://github.com/orgs/ros2/projects/23#card-58333054)

No, not exactly.  We've just been fixing them as we see them.  I think we've now gotten all of them :).

**Comment by aprotyas** [comment]
CI: (build: `--packages-above-and-dependencies rqt_gui_py` test: `--packages-above rqt_gui_py`)

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14880/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9629/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12546/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15039/)

**Comment by clalancette** [comment]
I'm going to go ahead and merge this.  Thanks @aprotyas !

**Pull request merged**
