### PR TITLE
Proposed replacement for rqt.svg

### PR DESCRIPTION
**Pull request by LucidOne**
A visually appealing upgrade of the rqt icon.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
"Visually appealing" might be subjective... ;-) But I think it is not a good thing to remove some of the dots for the "rqt" text since it does not follow the ROS style guide.

**Comment by LucidOne** [comment]
How about if I remove the RQT and leave the monitor to make it more of an icon?

**Comment by dirk-thomas** [comment]
I think that would make it better - and people should associate the icon with rqt so a label should not be necessary.

It might be an issue that the icon does not have any padding at the border. I think that was an issue when I added the current icon in the first place. If it fits in fine I will go ahead and merge the modified version after you committed it.

**Comment by wjwwood** [comment]
@IHeartRobotics what about the icon in #89, thoughts?

**Comment by wjwwood** [comment]
I exported it to a png with inkscape (hopefully it looks how you intended) for reference:

rqt

@spaepcke

**Comment by dirk-thomas** [comment]
Closing in favor of #89.

**Pull request closed without merging**
