### PR TITLE
improve startup time

### PR DESCRIPTION
**Pull request by dirk-thomas**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
This pull request should resolve ros-visualization/rqt_common_plugins#172. It depends on ros-visualization/qt_gui_core#28. Together they implement a generic way of caching plugin discovery information for both supported languages (Py & C++) and reuse rospkg.RosPack instances throughout the code.

The startup time should be significantly faster - on my machine `rqt` comes up in about one second.

@wjwwood @ablasdel @DorianScholz @IHeartRobotics Please review and try running the changes from this branch and from the corresponding branch of qt_gui_core. (rqt_bag needs a tiny patch to continue working with the modified plugin provider API ros-visualization/rqt_common_plugins#189 - all other plugins should immediately benefit from the improvements.)

**Comment by dirk-thomas** [comment]
The C++ part of ros-visualization/qt_gui_core#28 depends on the latest release of pluginlib 1.9.23 which is currently only in shadow-fixed.

**Comment by wjwwood** [comment]
+1 much faster

**Comment by ablasdel** [comment]
+1!

**Comment by DorianScholz** [comment]
looks good
+1

**Pull request merged**
